spring:
  jackson:
    default-property-inclusion: non_empty
    deserialization:
      #允许对象忽略json中不存在的属性
      fail_on_unknown_properties: false
    serialization:
      #忽略无法转换的对象
      fail_on_empty_beans: false
      WRITE_DATES_AS_TIMESTAMPS: false
  redis:
    database: 0
    host: 172.16.3.197
    port: 6379
    password: daohaode4
    timeout: 2000
    jedis:
      pool:
        #最大连接数
        max-active: 8
        #最大阻塞等待时间(负数表示没限制)
        max-wait: -1
        #最大空闲
        max-idle: 8
        #最小空闲
        min-idle: 0
